name: PHP Version Check

on:
  push:
    branches:
      - test_1
      - test_2

jobs:
  run-in-container-test_1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test_1' 
    container:
      image: node:18 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Node.js script for test_1
        run: |
          echo "console.log('Rama 1 – Print 1');" > script.js
          echo "console.log('Rama 1 – Print 2');" >> script.js
          echo "console.log('Rama 1 – Print 3');" >> script.js
          node script.js  # Ejecutar el script de Node.js

  run-in-container-test_2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test_2'  
    container:
      image: node:18  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Node.js script for test_2
        run: |
          echo "console.log('Rama 2 – Print 1');" > script.js
          echo "console.log('Rama 2 – Print 2');" > script.js
          echo "console.log('Rama 2 – Print 3');" > script.js
          node script.js  # Ejecutar el script de Node.js
