name: Imprimir en consola según la rama

on:
  push:
    branches:
      - "test_1"
      - "test_2"

jobs:
  print_messages:
    runs-on: ubuntu-latest
    container:
      image: node:18  # Usamos un contenedor con Node.js, pero puedes usar otro contenedor de tu preferencia

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Imprimir mensajes para test_1
        if: github.ref == 'refs/heads/test_1'
        run: |
          echo "Rama 1 Print 1"
          echo "Rama 2 Print 2"
          echo "Rama 3 Print 3"

      - name: Imprimir mensajes para test_2
        if: github.ref == 'refs/heads/test_2'
        run: |
          echo "Test_2 Print 1"
          echo "Test_2 Print 2"
          echo "Test_2 Print 3"
